### ISSUE TITLE
Matrix.cpp Review

### ISSUE THREAD

**Issue by qtuancr261** [thaiduong1011/LinhTinh#3]
Constructor : _for (int i = 0; i < r; i++){
		          p[i] = new float[i]; // i ? column mới đúng chứ nhỉ 
                     }

Cẩn thận hàm này Matrix& operator=(const float& number); // nên để là float number thôi là đc
matrix.~Matrix(); // Destructor sẽ đc gọi tự động, ko cần gọi ra như này 
=> đã build and Run thử chưa đó . Này đi thi là toi nha :))

**Comment by thaiduong1011** [comment]
run rồi mà nhỉ

**Comment by thaiduong1011** [comment]
gọi tự động sao cần xây dựng hàm Destroy đó chi -_-

**Comment by qtuancr261** [comment]
Compiler tự gọi, nhưng mà mặc định hàm destructor của nó ko có delete đc mấy cái biến đc cấp phát động, nên mình phải định nghĩa lại để xoá cái mảng 2 chiều. Kết thúc ct thì compiler sẽ tự động gọi hàm này của mình. Thử cout gì trong hàm này đi, rôi ko gọi trong main, xem thử nó có cout ra ko :

**Comment by qtuancr261** [comment]
Okie :D . Trong một class nếu có các thuộc tính được cấp phát động thì mình phải định nghĩa lại destructor để nó có thể thu hồi lại bộ nhớ cấp phát cho các thuộc tính này, do default destructor của compiler ko tự động thu dọn đc các biến được cấp phát động . Nhớ rằng mình chỉ định nghĩa thôi, việc gọi là do compiler gọi.

**Comment by qtuancr261** [comment]
![screenshot_20180925_224603](https://user-images.githubusercontent.com/26165668/46026140-cbf2e500-c114-11e8-8f2a-5cc41647303f.png)

**Comment by thaiduong1011** [comment]
ok
